#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
RUN dotnet --version
WORKDIR /src
COPY ["ChatBot.Pages/ChatBot.Pages.csproj", "ChatBot.Pages/"]
COPY ["ChatBot.Core/ChatBot.Core.csproj", "ChatBot.Core/"]
RUN dotnet restore "ChatBot.Pages/ChatBot.Pages.csproj"
COPY . .
WORKDIR "/src/ChatBot.Pages"
RUN dotnet build "ChatBot.Pages.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ChatBot.Pages.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ChatBot.Pages.dll"]